defaults: &defaults
  outputdir:  /Users/bsr/Desktop/starchives

users: &users
  0000:
    - testuser1
    - github
    - 328h9f9292h3829h4nf
  0001:
    - testuser2
    - gitlab
    - linv9dnkjb38o13of12