defaults: &defaults
  outputdir:  /Users/8br/Desktop/starchives

users: &users
  0000:
    - testuser1
    - github
    - 328h9f9292h3829h4nf
  0001:
    - testuser2
    - gitlab
    - linv9dnkjb38o13of12
  0002:
    - testuser3
    - gitlab
    - nof12invkl139djb38o
  0003:
    - testuser4
    - github
    - n38o139dnof1vlikjb2 
  0004:
    - testuser5
    - github
    - l38o139dnof12invkjb
  0005:
    - testuser6
    - gitlab
    - 38o123linvkjb43212 